# Generated by Django 5.1 on 2024-08-21 14:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0002_startupprograma_activo_delete_inscripcion'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(help_text='Título del programa', max_length=255)),
                ('descripcion', wagtail.fields.RichTextField(blank=True, help_text='Descripción del programa')),
                ('duracion', models.CharField(blank=True, help_text='Duración del programa', max_length=50)),
                ('requisitos', wagtail.fields.RichTextField(blank=True, help_text='Requisitos para participar en el programa')),
                ('imagen', models.ForeignKey(blank=True, help_text='Imagen del programa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Página de Programa',
                'verbose_name_plural': 'Páginas de Programas',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramaBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='programa_startup.programapage')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='programa_startup.programapage')),
            ],
        ),
    ]
