# Generated by Django 5.1 on 2024-08-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0003_programapage_programabeneficio_criterioevaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='criterios_evaluacion',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='programa',
            name='pagina_programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='programa_startup.programapage'),
        ),
        migrations.AddField(
            model_name='programapage',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fin del programa', null=True),
        ),
        migrations.AddField(
            model_name='programapage',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Inicio del programa', null=True),
        ),
    ]
