# Generated by Django 5.1 on 2024-08-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0004_remove_programa_beneficios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='pagina_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='programa_startup.programapage'),
        ),
    ]
