# Generated by Django 5.1 on 2024-08-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0007_cronogramaitem_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programapage',
            options={'verbose_name': 'Programa Page', 'verbose_name_plural': 'Programas Page'},
        ),
    ]
