# Generated by Django 5.1 on 2024-08-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0008_alter_programapage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_startups', to='programa_startup.programa'),
        ),
    ]
