# Generated by Django 5.1 on 2024-08-25 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0009_alter_startup_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='pagina_programa',
        ),
        migrations.AlterField(
            model_name='startup',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_startups', to='programa_startup.programapage'),
        ),
        migrations.AlterField(
            model_name='startupprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups_participantes', to='programa_startup.programapage'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='programa_startup.programapage'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa_startup.programapage'),
        ),
    ]
