# Generated by Django 5.1 on 2024-08-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0010_remove_programa_pagina_programa_and_more'),
        ('usuarios', '0008_alter_mentor_programa_alter_mentoria_programa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programa',
        ),
    ]
