# Generated by Django 5.1 on 2024-08-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0012_modulo_imagen_sesion_delete_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas/')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('recurso', 'Recurso')], default='tarea', max_length=10)),
                ('bloqueado', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='programa_startup.sesion')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
