# Generated by Django 5.1 on 2024-08-25 16:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0013_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='programa',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='programa_startup.programapage'),
        ),
    ]
