# Generated by Django 5.1 on 2024-08-25 18:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0014_alter_modulo_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sprint',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='programa_startup.sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='modulo',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='programa_startup.modulo'),
        ),
    ]
