# Generated by Django 5.1 on 2024-08-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0015_alter_sesion_sprint_alter_sprint_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='sesion',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
