# Generated by Django 5.1 on 2024-08-25 19:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0016_remove_sprint_modulo_remove_sesion_sprint_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos/')),
                ('programa', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos', to='programa_startup.programapage')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['orden'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='startup',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
