# Generated by Django 5.1 on 2024-08-25 19:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0017_modulo_remove_entregable_sprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('modulo', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='programa_startup.modulo')),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('lectura', 'Lectura'), ('ejercicio', 'Ejercicio'), ('material', 'Material Adicional')], max_length=50)),
                ('orden', models.PositiveIntegerField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='sesiones/')),
                ('url_externa', models.URLField(blank=True, max_length=255, null=True)),
                ('sprint', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='programa_startup.sprint')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_entregables', to='programa_startup.startup')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_entregables', to='programa_startup.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas/')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('recurso', 'Recurso')], default='tarea', max_length=10)),
                ('bloqueado', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='programa_startup.sesion')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
