# Generated by Django 5.1 on 2024-08-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0019_alter_modulo_options_alter_sesion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
