# Generated by Django 5.1 on 2024-08-26 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0021_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fecha_inscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='progreso',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.DeleteModel(
            name='StartupPrograma',
        ),
    ]
