# Generated by Django 5.1 on 2024-08-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0022_startup_activo_startup_fecha_inscripcion_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='startup',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ForeignKey(blank=True, help_text='Imagen del evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Programa', 'Programa'), ('General', 'General')], max_length=50),
        ),
    ]
