# Generated by Django 5.1 on 2024-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0023_alter_evento_options_remove_evento_programa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
