# Generated by Django 5.1 on 2024-08-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0025_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento Page', 'verbose_name_plural': 'Eventos Pages'},
        ),
    ]
