# Generated by Django 5.1 on 2024-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0027_evento_url_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
