# Generated by Django 5.1 on 2024-08-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0028_sesion_completada_tarea_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='entregado',
        ),
    ]
