# Generated by Django 5.1 on 2024-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0030_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
