# Generated by Django 5.1 on 2024-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0031_alter_logro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
