# Generated by Django 5.1 on 2024-09-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0032_alter_logro_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logro',
            old_name='fecha',
            new_name='fecha_logro',
        ),
    ]
