# Generated by Django 5.1 on 2024-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0033_rename_fecha_logro_fecha_logro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
