# Generated by Django 5.1 on 2024-10-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0034_alter_logro_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrantestartup',
            options={'verbose_name': 'Integrante de la Startup', 'verbose_name_plural': 'Integrantes de la Startup'},
        ),
    ]
