# Generated by Django 5.1 on 2024-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_startup', '0035_alter_integrantestartup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Describe claramente qué debe entregar el emprendedor', null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Solo necesario para entregables', null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(blank=True, choices=[('modelo_negocio', 'Modelo de Negocio'), ('plan_financiero', 'Plan Financiero'), ('investigacion_mercado', 'Investigación de Mercado'), ('pitch', 'Pitch Deck'), ('guia', 'Guía'), ('material', 'Material de Apoyo'), ('material_adicional', 'Material Adicional')], default='Material de Apoyo', help_text='Selecciona el tipo de entregable o recurso. Si está en blanco, se derivará del tipo de la sesión.', max_length=50),
        ),
    ]
