# Generated by Django 5.1 on 2024-10-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellidos'),
        ),
    ]
