# Generated by Django 5.1 on 2024-10-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aula', '0003_remove_driver_first_name_remove_driver_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='constructors',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='constructor',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='author',
        ),
        migrations.RemoveField(
            model_name='race',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='race',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tags_content_609291_idx',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
        migrations.DeleteModel(
            name='Constructor',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='HistoricalDriver',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Standing',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
