# Generated by Django 5.1 on 2024-10-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aula', '0004_remove_race_circuit_remove_driver_constructors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
