# Generated by Django 5.1 on 2024-08-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='ocupacion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
