# Generated by Django 5.1 on 2024-08-16 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_mentor_ocupacion_customuser_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='precio_por_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mentor',
            name='programa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='puede_cobrar',
            field=models.BooleanField(default=False),
        ),
    ]
