# Generated by Django 5.1 on 2024-08-31 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_mentoria_programa'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
