# Generated by Django 5.1 on 2024-09-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
