# Generated by Django 5.1 on 2024-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_delete_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoria',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], max_length=20),
        ),
    ]
