# Generated by Django 5.1 on 2024-10-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
    ]
