# Generated by Django 5.1 on 2024-10-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
